"""Brief de recherche, profil client, type d'operation, statut, delai de livraison, prix de revente

Revision ID: badf5ba02059
Revises: c3feb3cc40bb
Create Date: 2026-08-17 14:04:44.940826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badf5ba02059'
down_revision = 'c3feb3cc40bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('type_bien', sa.String(length=40), nullable=False),
    sa.Column('standing', sa.String(length=40), nullable=True),
    sa.Column('zone_recherchee', sa.String(length=160), nullable=True),
    sa.Column('superficie_min', sa.Float(), nullable=True),
    sa.Column('superficie_max', sa.Float(), nullable=True),
    sa.Column('nb_chambres', sa.Integer(), nullable=True),
    sa.Column('nb_salles_bains', sa.Integer(), nullable=True),
    sa.Column('nb_salons', sa.Integer(), nullable=True),
    sa.Column('etage', sa.String(length=40), nullable=True),
    sa.Column('orientation', sa.String(length=40), nullable=True),
    sa.Column('commodites', sa.Text(), nullable=True),
    sa.Column('type_acquisition', sa.String(length=20), nullable=False),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('mode_financement', sa.String(length=20), nullable=False),
    sa.Column('objectif', sa.String(length=20), nullable=False),
    sa.Column('horizon_annees', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situation_professionnelle', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('nationalite', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('budget_disponible', sa.Float(), nullable=True))

    # Les projets existants sont des opérations locatives en phase de
    # recherche, sur un bien déjà livré : d'où les valeurs par défaut, posées
    # le temps de la migration puis retirées du schéma.
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_operation', sa.String(length=20),
                                      nullable=False, server_default='locatif'))
        batch_op.add_column(sa.Column('statut', sa.String(length=20),
                                      nullable=False, server_default='recherche'))
        batch_op.add_column(sa.Column('delai_livraison_mois', sa.Integer(),
                                      nullable=False, server_default='0'))

    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.alter_column('type_operation', server_default=None)
        batch_op.alter_column('statut', server_default=None)
        batch_op.alter_column('delai_livraison_mois', server_default=None)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prix_revente', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_column('prix_revente')

    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.drop_column('delai_livraison_mois')
        batch_op.drop_column('statut')
        batch_op.drop_column('type_operation')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('budget_disponible')
        batch_op.drop_column('nationalite')
        batch_op.drop_column('situation_professionnelle')

    op.drop_table('briefs')
    # ### end Alembic commands ###
