"""Schéma initial : users, zones, clients, projets, travaux, scenarios

Revision ID: c3feb3cc40bb
Revises: 
Create Date: 2026-07-19 00:27:08.132502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3feb3cc40bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('zone_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('devise', sa.String(length=8), nullable=False),
    sa.Column('taux_enregistrement', sa.Float(), nullable=False),
    sa.Column('taux_publicite_fonciere', sa.Float(), nullable=False),
    sa.Column('taux_notaire', sa.Float(), nullable=False),
    sa.Column('taux_frais_divers', sa.Float(), nullable=False),
    sa.Column('taux_imposition_defaut', sa.Float(), nullable=False),
    sa.Column('par_defaut', sa.Boolean(), nullable=False),
    sa.Column('personnalisable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=160), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('surface_m2', sa.Float(), nullable=True),
    sa.Column('prix_bien', sa.Float(), nullable=False),
    sa.Column('budget_travaux', sa.Float(), nullable=False),
    sa.Column('taux_frais_override', sa.Float(), nullable=True),
    sa.Column('loyer_mensuel', sa.Float(), nullable=False),
    sa.Column('charges_copro_annuelles', sa.Float(), nullable=False),
    sa.Column('assurance_annuelle', sa.Float(), nullable=False),
    sa.Column('frais_gestion_pct', sa.Float(), nullable=False),
    sa.Column('vacance_pct', sa.Float(), nullable=False),
    sa.Column('entretien_annuel', sa.Float(), nullable=False),
    sa.Column('taxe_annuelle', sa.Float(), nullable=False),
    sa.Column('taux_imposition_override', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone_presets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lignes_travaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=160), nullable=False),
    sa.Column('categorie', sa.String(length=80), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('apport', sa.Float(), nullable=False),
    sa.Column('taux_interet', sa.Float(), nullable=False),
    sa.Column('taux_assurance', sa.Float(), nullable=False),
    sa.Column('duree_annees', sa.Integer(), nullable=False),
    sa.Column('horizon_annees', sa.Integer(), nullable=False),
    sa.Column('revalorisation_loyer_pct', sa.Float(), nullable=False),
    sa.Column('revalorisation_bien_pct', sa.Float(), nullable=False),
    sa.Column('frais_revente_pct', sa.Float(), nullable=False),
    sa.Column('taux_actualisation', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenarios')
    op.drop_table('lignes_travaux')
    op.drop_table('projets')
    op.drop_table('clients')
    op.drop_table('zone_presets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
